language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-25.0.2
    - android-25

script: "./gradlew build --stacktrace"